### ISSUE TITLE
terraria

### ISSUE THREAD

**Issue by hxzhao527** [hxzhao527/game#1]
## docker-compose.yaml
```yaml
version: "3"
services:
  terraria:
    image: beardedio/terraria:vanilla-1.4.0.4
    ports:
      - "7777:7777"
    restart: unless-stopped
    environment:
      - world=The_Common_Tropic.wld
    volumes:
      - ./config:/config
    tty: true
    stdin_open: true
```
